"""
Maps goodbooks-10k's raw Goodreads folksonomy tags to a curated set of
genre/category labels.

The raw tags are user-generated "shelves," so most of the top tags by
volume aren't genres at all - they're personal organization ("to-read",
"currently-reading", "owned", "kindle", "audiobook", "dnf", "read-in-2015")
or specific authors ("stephen-king", "agatha-christie"). This map keeps
only the tags that actually describe what kind of book something is, and
collapses obvious synonyms/misspellings ("sci-fi"/"scifi"/"sf" -> the same
canonical genre) so the content model isn't needlessly fragmented.

This list was built by hand from `tags.csv`/`book_tags.csv` - it is not
exhaustive, but it covers every tag with enough volume to matter (see
`explore_tags.py`-style inspection during development).
"""

GENRE_TAG_MAP = {
    # fiction / literary
    "fiction": "fiction",
    "literary-fiction": "literary-fiction",
    "literary": "literary-fiction",
    "literature": "literary-fiction",
    "general-fiction": "literary-fiction",
    "novel": "literary-fiction",
    "novels": "literary-fiction",
    "contemporary": "contemporary",
    "contemporary-fiction": "contemporary",
    "classics": "classics",
    "classic": "classics",
    "classic-literature": "classics",
    "american-literature": "classics",
    "british-literature": "classics",
    # speculative
    "fantasy": "fantasy",
    "high-fantasy": "fantasy",
    "epic-fantasy": "fantasy",
    "sci-fi-fantasy": "fantasy",
    "fantasy-sci-fi": "fantasy",
    "fantasy-scifi": "fantasy",
    "scifi-fantasy": "fantasy",
    "science-fiction-fantasy": "fantasy",
    "science-fiction": "science-fiction",
    "sci-fi": "science-fiction",
    "scifi": "science-fiction",
    "sf": "science-fiction",
    "speculative-fiction": "science-fiction",
    "urban-fantasy": "urban-fantasy",
    "paranormal": "paranormal",
    "supernatural": "paranormal",
    "vampires": "paranormal",
    "vampire": "paranormal",
    "werewolves": "paranormal",
    "witches": "paranormal",
    "demons": "paranormal",
    "ghosts": "paranormal",
    "shifters": "paranormal",
    "shapeshifters": "paranormal",
    "dystopian": "dystopian",
    "dystopia": "dystopian",
    "post-apocalyptic": "dystopian",
    "steampunk": "steampunk",
    "magical-realism": "magical-realism",
    "time-travel": "science-fiction",
    "mythology": "mythology",
    "fairy-tales": "fairy-tales",
    # mystery / thriller / crime
    "mystery": "mystery",
    "mysteries": "mystery",
    "mystery-thriller": "mystery",
    "mystery-suspense": "mystery",
    "mystery-crime": "mystery",
    "crime-mystery": "mystery",
    "detective": "mystery",
    "thriller": "thriller",
    "thrillers": "thriller",
    "suspense": "thriller",
    "crime": "crime",
    "crime-fiction": "crime",
    "horror": "horror",
    # romance
    "romance": "romance",
    "contemporary-romance": "romance",
    "historical-romance": "romance",
    "paranormal-romance": "romance",
    "romantic-suspense": "romance",
    "chick-lit": "romance",
    "chicklit": "romance",
    "erotica": "romance",
    "pnr": "romance",
    # historical / war
    "historical-fiction": "historical-fiction",
    "historical": "historical-fiction",
    "history": "history",
    "war": "history",
    "wwii": "history",
    "military": "history",
    "20th-century": "history",
    "19th-century": "history",
    # ya / childrens
    "young-adult": "young-adult",
    "ya": "young-adult",
    "ya-fiction": "young-adult",
    "ya-books": "young-adult",
    "ya-lit": "young-adult",
    "young-adult-fiction": "young-adult",
    "teen": "young-adult",
    "teen-fiction": "young-adult",
    "new-adult": "young-adult",
    "coming-of-age": "young-adult",
    "children": "childrens",
    "childrens": "childrens",
    "children-s": "childrens",
    "children-s-books": "childrens",
    "childrens-books": "childrens",
    "kids": "childrens",
    "kids-books": "childrens",
    "picture-books": "childrens",
    "picture-book": "childrens",
    "juvenile": "childrens",
    "juvenile-fiction": "childrens",
    "middle-grade": "childrens",
    "children-s-literature": "childrens",
    "children-s-lit": "childrens",
    # graphic / visual
    "graphic-novels": "graphic-novels",
    "graphic-novel": "graphic-novels",
    "comics": "graphic-novels",
    "comic": "graphic-novels",
    "comic-books": "graphic-novels",
    "graphic-novels-comics": "graphic-novels",
    "comics-graphic-novels": "graphic-novels",
    "manga": "graphic-novels",
    # nonfiction categories
    "non-fiction": "nonfiction",
    "nonfiction": "nonfiction",
    "biography": "biography",
    "biographies": "biography",
    "biography-memoir": "biography",
    "memoir": "biography",
    "memoirs": "biography",
    "autobiography": "biography",
    "science": "science",
    "philosophy": "philosophy",
    "psychology": "psychology",
    "self-help": "self-help",
    "business": "business",
    "economics": "business",
    "religion": "religion",
    "christian": "religion",
    "christian-fiction": "religion",
    "spirituality": "religion",
    "spiritual": "religion",
    "politics": "politics",
    "feminism": "politics",
    "travel": "travel",
    "food": "food",
    "cookbooks": "food",
    "art": "art",
    "music": "music",
    "essays": "essays",
    # tone / form
    "humor": "humor",
    "humour": "humor",
    "comedy": "humor",
    "funny": "humor",
    "poetry": "poetry",
    "plays": "drama",
    "drama": "drama",
    "short-stories": "short-stories",
    "adventure": "adventure",
    "action": "adventure",
    "action-adventure": "adventure",
    "survival": "adventure",
    "lgbt": "lgbt",
}

# canonical genre -> broad "section" a real bookstore might use, purely for
# a friendlier inventory legend / UI grouping.
GENRE_SECTION = {
    "fiction": "Fiction",
    "literary-fiction": "Fiction",
    "contemporary": "Fiction",
    "classics": "Fiction",
    "fantasy": "Sci-Fi & Fantasy",
    "science-fiction": "Sci-Fi & Fantasy",
    "urban-fantasy": "Sci-Fi & Fantasy",
    "paranormal": "Sci-Fi & Fantasy",
    "dystopian": "Sci-Fi & Fantasy",
    "steampunk": "Sci-Fi & Fantasy",
    "magical-realism": "Sci-Fi & Fantasy",
    "mythology": "Sci-Fi & Fantasy",
    "fairy-tales": "Sci-Fi & Fantasy",
    "mystery": "Mystery & Thriller",
    "thriller": "Mystery & Thriller",
    "crime": "Mystery & Thriller",
    "horror": "Horror",
    "romance": "Romance",
    "historical-fiction": "Historical Fiction",
    "history": "History",
    "young-adult": "Young Adult",
    "childrens": "Children's",
    "graphic-novels": "Graphic Novels & Comics",
    "nonfiction": "Nonfiction",
    "biography": "Biography & Memoir",
    "science": "Science",
    "philosophy": "Philosophy",
    "psychology": "Psychology",
    "self-help": "Self-Help",
    "business": "Business",
    "religion": "Religion & Spirituality",
    "politics": "Politics & Society",
    "travel": "Travel",
    "food": "Food & Cooking",
    "art": "Art",
    "music": "Music",
    "essays": "Essays",
    "humor": "Humor",
    "poetry": "Poetry",
    "drama": "Drama",
    "short-stories": "Short Stories",
    "adventure": "Adventure",
    "lgbt": "LGBTQ+",
}
